---
- name: Fetch all existing orgs (api)
  uri:
    url: "{{ grafana_api_url }}/api/orgs"
    user: "{{ grafana_security.admin_user }}"
    password: "{{ grafana_security.admin_password }}"
    force_basic_auth: true
    body_format: json
  no_log: true
  register: _grafana_organisations

- name: Debug _grafana_organisations
  debug:
    var: _grafana_organisations
  when:
    - _grafana_organisations is defined
  tags:
    - never
    - debug

- name: Create orgs not already present (api)
  uri:
    url: "{{ grafana_api_url }}/api/orgs"
    user: "{{ grafana_security.admin_user }}"
    password: "{{ grafana_security.admin_password }}"
    force_basic_auth: true
    method: POST
    body_format: json
    body: "{{
              grafana_organisations
              | selectattr('name', 'equalto', item) | first | to_json
          }}"
  no_log: true
  register: _grafana_organisations_created
  changed_when: true
  with_items:
    - "{{
          (
            grafana_organisations
            | map(attribute='name')
            | list
          )
          | difference(
                _grafana_organisations['json']
                | map(attribute='name')
                | list
            )
      }}"

- name: Debug _grafana_organisations_created
  debug:
    var: _grafana_organisations_created
  when:
    - _grafana_organisations_created is defined
  tags:
    - never
    - debug
