---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: buster
    pre_build_image: true
    image: quay.io/paulfantom/molecule-systemd:debian-10
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: fedora
    pre_build_image: true
    image: quay.io/paulfantom/molecule-systemd:fedora-30
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - python3
provisioner:
  name: ansible
  playbooks:
    prepare: ../default/prepare.yml
    converge: playbook.yml
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: testinfra
